# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_PUBLIC_APPWRITE_PROJECT_ID
ARG VITE_PUBLIC_APPWRITE_PROJECT_NAME
ARG VITE_PUBLIC_APPWRITE_ENDPOINT
ARG VITE_PUBLIC_APPWRITE_DATABASE_ID
ARG VITE_PUBLIC_APPWRITE_BUCKET
ARG VITE_PUBLIC_APP_ORIGIN
ARG API_WORKLOADHUB_ORIGIN

ENV VITE_PUBLIC_APPWRITE_PROJECT_ID=$VITE_PUBLIC_APPWRITE_PROJECT_ID \
    VITE_PUBLIC_APPWRITE_PROJECT_NAME=$VITE_PUBLIC_APPWRITE_PROJECT_NAME \
    VITE_PUBLIC_APPWRITE_ENDPOINT=$VITE_PUBLIC_APPWRITE_ENDPOINT \
    VITE_PUBLIC_APPWRITE_DATABASE_ID=$VITE_PUBLIC_APPWRITE_DATABASE_ID \
    VITE_PUBLIC_APPWRITE_BUCKET=$VITE_PUBLIC_APPWRITE_BUCKET \
    VITE_PUBLIC_APP_ORIGIN=$VITE_PUBLIC_APP_ORIGIN \
    VITE_PUBLIC_API_WORKLOADHUB_ORIGIN=$API_WORKLOADHUB_ORIGIN

RUN npm run build

FROM nginx:1.27-alpine AS runtime
RUN apk add --no-cache curl \
 && rm -f /etc/nginx/conf.d/default.conf

COPY deploy/nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

HEALTHCHECK --interval=15s --timeout=3s --retries=5 \
  CMD curl -fsS http://127.0.0.1:8080/health >/dev/null || exit 1

CMD ["nginx", "-g", "daemon off;"]
